#############################################################################
# Makefile for building: bin/mSerialPortTools
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 3? 9 15:06:51 2018
# Project:  mSerialPortTools.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile mSerialPortTools.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Itemp/moc -Itemp/ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = temp/obj/

####### Files

SOURCES       = main.cpp \
		qextserialport.cpp \
		frmmain.cpp \
		qextserialport_unix.cpp temp/moc/moc_frmmain.cpp \
		temp/rcc/qrc_main.cpp
OBJECTS       = temp/obj/main.o \
		temp/obj/qextserialport.o \
		temp/obj/frmmain.o \
		temp/obj/qextserialport_unix.o \
		temp/obj/moc_frmmain.o \
		temp/obj/qrc_main.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		mSerialPortTools.pro
QMAKE_TARGET  = mSerialPortTools
DESTDIR       = bin/
TARGET        = bin/mSerialPortTools

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): temp/ui/ui_frmmain.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mSerialPortTools.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile mSerialPortTools.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_off.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mSerialPortTools.pro

dist: 
	@$(CHK_DIR_EXISTS) temp/obj/mSerialPortTools1.0.0 || $(MKDIR) temp/obj/mSerialPortTools1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/obj/mSerialPortTools1.0.0/ && $(COPY_FILE) --parents frmmain.h qextserialport_global.h qextserialport.h myhelper.h temp/obj/mSerialPortTools1.0.0/ && $(COPY_FILE) --parents main.qrc temp/obj/mSerialPortTools1.0.0/ && $(COPY_FILE) --parents main.cpp qextserialport.cpp frmmain.cpp qextserialport_unix.cpp temp/obj/mSerialPortTools1.0.0/ && $(COPY_FILE) --parents frmmain.ui temp/obj/mSerialPortTools1.0.0/ && (cd `dirname temp/obj/mSerialPortTools1.0.0` && $(TAR) mSerialPortTools1.0.0.tar mSerialPortTools1.0.0 && $(COMPRESS) mSerialPortTools1.0.0.tar) && $(MOVE) `dirname temp/obj/mSerialPortTools1.0.0`/mSerialPortTools1.0.0.tar.gz . && $(DEL_FILE) -r temp/obj/mSerialPortTools1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: temp/moc/moc_frmmain.cpp temp/moc/moc_qextserialport.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/moc/moc_frmmain.cpp temp/moc/moc_qextserialport.cpp
temp/moc/moc_frmmain.cpp: qextserialport.h \
		qextserialport_global.h \
		frmmain.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) frmmain.h -o temp/moc/moc_frmmain.cpp

temp/moc/moc_qextserialport.cpp: qextserialport_global.h \
		qextserialport.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qextserialport.h -o temp/moc/moc_qextserialport.cpp

compiler_rcc_make_all: temp/rcc/qrc_main.cpp
compiler_rcc_clean:
	-$(DEL_FILE) temp/rcc/qrc_main.cpp
temp/rcc/qrc_main.cpp: main.qrc \
		main.png \
		qt_zh_CN.qm
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name main main.qrc -o temp/rcc/qrc_main.cpp

compiler_image_collection_make_all: temp/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) temp/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: temp/ui/ui_frmmain.h
compiler_uic_clean:
	-$(DEL_FILE) temp/ui/ui_frmmain.h
temp/ui/ui_frmmain.h: frmmain.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic frmmain.ui -o temp/ui/ui_frmmain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

temp/obj/main.o: main.cpp frmmain.h \
		qextserialport.h \
		qextserialport_global.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/main.o main.cpp

temp/obj/qextserialport.o: qextserialport.cpp qextserialport.h \
		qextserialport_global.h \
		qextserialport_p.h \
		temp/moc/moc_qextserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/qextserialport.o qextserialport.cpp

temp/obj/frmmain.o: frmmain.cpp frmmain.h \
		qextserialport.h \
		qextserialport_global.h \
		temp/ui/ui_frmmain.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/frmmain.o frmmain.cpp

temp/obj/qextserialport_unix.o: qextserialport_unix.cpp qextserialport.h \
		qextserialport_global.h \
		qextserialport_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/qextserialport_unix.o qextserialport_unix.cpp

temp/obj/moc_frmmain.o: temp/moc/moc_frmmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_frmmain.o temp/moc/moc_frmmain.cpp

temp/obj/qrc_main.o: temp/rcc/qrc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/qrc_main.o temp/rcc/qrc_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

